config/routes.rb
GistsTemplate::Application.routes.draw do
  resources :users, :only => [:new, :create, :show]
  resource :session, :only => [:new, :create, :destroy]

  root :to => "users#new"

  resources :gists do
    resource :favorite, :only => [:create, :destroy]
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :gist_id, :user_id

  belongs_to :user
  belongs_to :gist
end

app/models/gist.rb
class Gist < ActiveRecord::Base
  attr_accessible :body, :title, :user_id

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, foreign_key: :user_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :password, :username
  attr_reader :password

  validates :username, :password_digest, :presence => true
  validates :password, :length => { :minimum => 3 }

  has_many :favorites
  has_many :favorite_gists, through: :favorites, foreign_key: :gist_id

  def password
    @password || self.password_digest
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  def redirect_logged_in_user
    if logged_in? 
      flash[:errors] ||= []
      flash[:errors] << "You are already logged in"
      redirect_to current_user 
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  respond_to :json

  def create
    @fave = Favorite.new({:user_id => current_user.id, :gist_id => params[:gist_id]})
    @fave.save
    @gist = Gist.new()
    respond_with(@gist)
  end

  def destroy
    @fave = Favorite.find_by_user_id_and_gist_id(current_user.id,params[:gist_id])
    @fave.destroy
    respond_with(@fave)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  respond_to :html, :json

  def index
    @gists = Gist.all
    @favorites = current_user.favorites
    @data = {gists: @gists, favorites: @favorites}
    respond_with(@data)
  end

  def create
  end

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_filter :redirect_logged_in_user, :only => [:new]

  def new
  end

  def create
    @user = User.find_by_username(params[:user][:username])

    if @user && @user.verify_password(params[:user][:password])
      login_user(@user)
      redirect_to gists_url
    else
      flash[:errors] ||= []
      flash[:errors] << "Incorrect username or password"
      redirect_to new_session_path
    end
  end

  def destroy
    logout_user
    flash[:errors] ||= []
    flash[:errors] << "You have been successfully logged out"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_logged_in_user, :only => [:new]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user(@user)
      redirect_to @user
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @user.errors.full_messages.to_sentence
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user 
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user(user)
    token = SecureRandom.base64(16)

    user.session_token = token 
    session[:session_token] = token
    user.save
  end

  def logout_user
    token = SecureRandom.base64(12)
    current_user.session_token = token
    session[:session_token] = nil
    current_user.save
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gists/index.html.erb
<script type="application/javascript">
  GT.initialize({ gists: <%= @data[:gists].to_json.html_safe %>,
                  favorites: <%= @data[:favorites].to_json.html_safe %> });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GistsTemplate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="errors">
    <% flash[:errors].try(:each) do |error| %>
      <%= error %>
    <% end %>
  </div>
  <%= yield %>


  <div>
    <%= button_to "Logout", session_path, :method => "delete" %>
    Current User: <%= current_user %>
    Session Token: <%= session[:session_token] %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1> Sign Up</h1>

<form action="/users" method="post">
  <label>Username: <input type="text" name="user[username]" value="<%= @user.username %>" /></label>
  <label>Password: <input type="password" name="user[password]" /></label>
  <input type="submit" value="Sign Up" />
</form>

<p>
  <%= link_to "Login", new_session_path %>
</p>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Page </h1>